package model;
// Generated Oct 3, 2017 1:01:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Abastecimiento generated by hbm2java
 */
public class Abastecimiento  implements java.io.Serializable {


     private Integer id;
     private EstadoEnvioAbastecimiento estadoEnvioAbastecimiento;
     private Local localByLocalIdDestino;
     private Local localByLocalIdOrigen;
     private String observacion;
     private Date fechaEnvio;
     private Date fechaRecepcion;
     private Set abastecimientoHasInsumos = new HashSet(0);

    public Abastecimiento() {
    }

	
    public Abastecimiento(Local localByLocalIdDestino) {
        this.localByLocalIdDestino = localByLocalIdDestino;
    }
    public Abastecimiento(EstadoEnvioAbastecimiento estadoEnvioAbastecimiento, Local localByLocalIdDestino, Local localByLocalIdOrigen, String observacion, Date fechaEnvio, Date fechaRecepcion, Set abastecimientoHasInsumos) {
       this.estadoEnvioAbastecimiento = estadoEnvioAbastecimiento;
       this.localByLocalIdDestino = localByLocalIdDestino;
       this.localByLocalIdOrigen = localByLocalIdOrigen;
       this.observacion = observacion;
       this.fechaEnvio = fechaEnvio;
       this.fechaRecepcion = fechaRecepcion;
       this.abastecimientoHasInsumos = abastecimientoHasInsumos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EstadoEnvioAbastecimiento getEstadoEnvioAbastecimiento() {
        return this.estadoEnvioAbastecimiento;
    }
    
    public void setEstadoEnvioAbastecimiento(EstadoEnvioAbastecimiento estadoEnvioAbastecimiento) {
        this.estadoEnvioAbastecimiento = estadoEnvioAbastecimiento;
    }
    public Local getLocalByLocalIdDestino() {
        return this.localByLocalIdDestino;
    }
    
    public void setLocalByLocalIdDestino(Local localByLocalIdDestino) {
        this.localByLocalIdDestino = localByLocalIdDestino;
    }
    public Local getLocalByLocalIdOrigen() {
        return this.localByLocalIdOrigen;
    }
    
    public void setLocalByLocalIdOrigen(Local localByLocalIdOrigen) {
        this.localByLocalIdOrigen = localByLocalIdOrigen;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public Set getAbastecimientoHasInsumos() {
        return this.abastecimientoHasInsumos;
    }
    
    public void setAbastecimientoHasInsumos(Set abastecimientoHasInsumos) {
        this.abastecimientoHasInsumos = abastecimientoHasInsumos;
    }




}


