package model;
// Generated Nov 7, 2017 7:30:44 PM by Hibernate Tools 4.3.1



/**
 * AbastecimientoHasInsumoId generated by hbm2java
 */
public class AbastecimientoHasInsumoId  implements java.io.Serializable {


     private int id;
     private int abastecimientoId;
     private int insumoId;

    public AbastecimientoHasInsumoId() {
    }

    public AbastecimientoHasInsumoId(int id, int abastecimientoId, int insumoId) {
       this.id = id;
       this.abastecimientoId = abastecimientoId;
       this.insumoId = insumoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAbastecimientoId() {
        return this.abastecimientoId;
    }
    
    public void setAbastecimientoId(int abastecimientoId) {
        this.abastecimientoId = abastecimientoId;
    }
    public int getInsumoId() {
        return this.insumoId;
    }
    
    public void setInsumoId(int insumoId) {
        this.insumoId = insumoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbastecimientoHasInsumoId) ) return false;
		 AbastecimientoHasInsumoId castOther = ( AbastecimientoHasInsumoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getAbastecimientoId()==castOther.getAbastecimientoId())
 && (this.getInsumoId()==castOther.getInsumoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getAbastecimientoId();
         result = 37 * result + this.getInsumoId();
         return result;
   }   


}


