package model;
// Generated Nov 13, 2017 12:33:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Abastecimiento generated by hbm2java
 */
public class Abastecimiento  implements java.io.Serializable {


     private Integer id;
     private EstadoAbastecimiento estadoAbastecimiento;
     private Local localByLocalIdOrigen;
     private Local localByLocalIdDestino;
     private String observacion;
     private Date fechaRecepcion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set abastecimientoHasInsumos = new HashSet(0);

    public Abastecimiento() {
    }

	
    public Abastecimiento(Local localByLocalIdDestino) {
        this.localByLocalIdDestino = localByLocalIdDestino;
    }
    public Abastecimiento(EstadoAbastecimiento estadoAbastecimiento, Local localByLocalIdOrigen, Local localByLocalIdDestino, String observacion, Date fechaRecepcion, Date fechaCreacion, Date fechaModificacion, Set abastecimientoHasInsumos) {
       this.estadoAbastecimiento = estadoAbastecimiento;
       this.localByLocalIdOrigen = localByLocalIdOrigen;
       this.localByLocalIdDestino = localByLocalIdDestino;
       this.observacion = observacion;
       this.fechaRecepcion = fechaRecepcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.abastecimientoHasInsumos = abastecimientoHasInsumos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EstadoAbastecimiento getEstadoAbastecimiento() {
        return this.estadoAbastecimiento;
    }
    
    public void setEstadoAbastecimiento(EstadoAbastecimiento estadoAbastecimiento) {
        this.estadoAbastecimiento = estadoAbastecimiento;
    }
    public Local getLocalByLocalIdOrigen() {
        return this.localByLocalIdOrigen;
    }
    
    public void setLocalByLocalIdOrigen(Local localByLocalIdOrigen) {
        this.localByLocalIdOrigen = localByLocalIdOrigen;
    }
    public Local getLocalByLocalIdDestino() {
        return this.localByLocalIdDestino;
    }
    
    public void setLocalByLocalIdDestino(Local localByLocalIdDestino) {
        this.localByLocalIdDestino = localByLocalIdDestino;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getAbastecimientoHasInsumos() {
        return this.abastecimientoHasInsumos;
    }
    
    public void setAbastecimientoHasInsumos(Set abastecimientoHasInsumos) {
        this.abastecimientoHasInsumos = abastecimientoHasInsumos;
    }




}


