package model;
// Generated Nov 13, 2017 12:33:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoAbastecimiento generated by hbm2java
 */
public class EstadoAbastecimiento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set abastecimientos = new HashSet(0);

    public EstadoAbastecimiento() {
    }

	
    public EstadoAbastecimiento(String nombre) {
        this.nombre = nombre;
    }
    public EstadoAbastecimiento(String nombre, Set abastecimientos) {
       this.nombre = nombre;
       this.abastecimientos = abastecimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAbastecimientos() {
        return this.abastecimientos;
    }
    
    public void setAbastecimientos(Set abastecimientos) {
        this.abastecimientos = abastecimientos;
    }




}


