package model;
// Generated Oct 3, 2017 1:01:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoEnvioAbastecimiento generated by hbm2java
 */
public class EstadoEnvioAbastecimiento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set abastecimientos = new HashSet(0);

    public EstadoEnvioAbastecimiento() {
    }

	
    public EstadoEnvioAbastecimiento(String nombre) {
        this.nombre = nombre;
    }
    public EstadoEnvioAbastecimiento(String nombre, Set abastecimientos) {
       this.nombre = nombre;
       this.abastecimientos = abastecimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAbastecimientos() {
        return this.abastecimientos;
    }
    
    public void setAbastecimientos(Set abastecimientos) {
        this.abastecimientos = abastecimientos;
    }




}


