package model;
// Generated Oct 25, 2017 6:15:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoAbastecimiento generated by hbm2java
 */
public class EstadoAbastecimiento  implements java.io.Serializable {


     private Integer int_;
     private String nombre;
     private Set abastecimientos = new HashSet(0);

    public EstadoAbastecimiento() {
    }

	
    public EstadoAbastecimiento(String nombre) {
        this.nombre = nombre;
    }
    public EstadoAbastecimiento(String nombre, Set abastecimientos) {
       this.nombre = nombre;
       this.abastecimientos = abastecimientos;
    }
   
    public Integer getInt_() {
        return this.int_;
    }
    
    public void setInt_(Integer int_) {
        this.int_ = int_;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAbastecimientos() {
        return this.abastecimientos;
    }
    
    public void setAbastecimientos(Set abastecimientos) {
        this.abastecimientos = abastecimientos;
    }




}


