package model;
// Generated Oct 3, 2017 1:01:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private String url;
     private Set insumos = new HashSet(0);

    public Imagen() {
    }

	
    public Imagen(String descripcion, String url) {
        this.descripcion = descripcion;
        this.url = url;
    }
    public Imagen(String descripcion, String url, Set insumos) {
       this.descripcion = descripcion;
       this.url = url;
       this.insumos = insumos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set insumos) {
        this.insumos = insumos;
    }




}


