package model;
// Generated Oct 3, 2017 1:01:15 AM by Hibernate Tools 4.3.1



/**
 * InsumoHasProveedorId generated by hbm2java
 */
public class InsumoHasProveedorId  implements java.io.Serializable {


     private int id;
     private int insumoId;
     private int proveedorId;

    public InsumoHasProveedorId() {
    }

    public InsumoHasProveedorId(int id, int insumoId, int proveedorId) {
       this.id = id;
       this.insumoId = insumoId;
       this.proveedorId = proveedorId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getInsumoId() {
        return this.insumoId;
    }
    
    public void setInsumoId(int insumoId) {
        this.insumoId = insumoId;
    }
    public int getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(int proveedorId) {
        this.proveedorId = proveedorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InsumoHasProveedorId) ) return false;
		 InsumoHasProveedorId castOther = ( InsumoHasProveedorId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getInsumoId()==castOther.getInsumoId())
 && (this.getProveedorId()==castOther.getProveedorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getInsumoId();
         result = 37 * result + this.getProveedorId();
         return result;
   }   


}


