package model;
// Generated Oct 3, 2017 1:01:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Insumo generated by hbm2java
 */
public class Insumo  implements java.io.Serializable {


     private Integer id;
     private Imagen imagen;
     private UnidadMedida unidadMedida;
     private String codBarra;
     private String nombre;
     private int stockMinimo;
     private String descripcion;
     private char estado;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set abastecimientoHasInsumos = new HashSet(0);
     private Set insumoHasProveedors = new HashSet(0);
     private Set localHasInsumos = new HashSet(0);

    public Insumo() {
    }

	
    public Insumo(Imagen imagen, UnidadMedida unidadMedida, String nombre, int stockMinimo, String descripcion, char estado, Date fechaCreacion) {
        this.imagen = imagen;
        this.unidadMedida = unidadMedida;
        this.nombre = nombre;
        this.stockMinimo = stockMinimo;
        this.descripcion = descripcion;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
    }
    public Insumo(Imagen imagen, UnidadMedida unidadMedida, String codBarra, String nombre, int stockMinimo, String descripcion, char estado, Date fechaCreacion, Date fechaModificacion, Set abastecimientoHasInsumos, Set insumoHasProveedors, Set localHasInsumos) {
       this.imagen = imagen;
       this.unidadMedida = unidadMedida;
       this.codBarra = codBarra;
       this.nombre = nombre;
       this.stockMinimo = stockMinimo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.abastecimientoHasInsumos = abastecimientoHasInsumos;
       this.insumoHasProveedors = insumoHasProveedors;
       this.localHasInsumos = localHasInsumos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getCodBarra() {
        return this.codBarra;
    }
    
    public void setCodBarra(String codBarra) {
        this.codBarra = codBarra;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(int stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getAbastecimientoHasInsumos() {
        return this.abastecimientoHasInsumos;
    }
    
    public void setAbastecimientoHasInsumos(Set abastecimientoHasInsumos) {
        this.abastecimientoHasInsumos = abastecimientoHasInsumos;
    }
    public Set getInsumoHasProveedors() {
        return this.insumoHasProveedors;
    }
    
    public void setInsumoHasProveedors(Set insumoHasProveedors) {
        this.insumoHasProveedors = insumoHasProveedors;
    }
    public Set getLocalHasInsumos() {
        return this.localHasInsumos;
    }
    
    public void setLocalHasInsumos(Set localHasInsumos) {
        this.localHasInsumos = localHasInsumos;
    }




}


