package model;
// Generated Oct 31, 2017 7:02:24 PM by Hibernate Tools 4.3.1



/**
 * LocalHasInsumoId generated by hbm2java
 */
public class LocalHasInsumoId  implements java.io.Serializable {


     private int id;
     private int localId;
     private int insumoId;

    public LocalHasInsumoId() {
    }

    public LocalHasInsumoId(int id, int localId, int insumoId) {
       this.id = id;
       this.localId = localId;
       this.insumoId = insumoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getLocalId() {
        return this.localId;
    }
    
    public void setLocalId(int localId) {
        this.localId = localId;
    }
    public int getInsumoId() {
        return this.insumoId;
    }
    
    public void setInsumoId(int insumoId) {
        this.insumoId = insumoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocalHasInsumoId) ) return false;
		 LocalHasInsumoId castOther = ( LocalHasInsumoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getLocalId()==castOther.getLocalId())
 && (this.getInsumoId()==castOther.getInsumoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getLocalId();
         result = 37 * result + this.getInsumoId();
         return result;
   }   


}


