package model;
// Generated Oct 31, 2017 7:02:24 PM by Hibernate Tools 4.3.1



/**
 * LocalHasUsuarioId generated by hbm2java
 */
public class LocalHasUsuarioId  implements java.io.Serializable {


     private int id;
     private int localId;
     private int usuarioId;

    public LocalHasUsuarioId() {
    }

    public LocalHasUsuarioId(int id, int localId, int usuarioId) {
       this.id = id;
       this.localId = localId;
       this.usuarioId = usuarioId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getLocalId() {
        return this.localId;
    }
    
    public void setLocalId(int localId) {
        this.localId = localId;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocalHasUsuarioId) ) return false;
		 LocalHasUsuarioId castOther = ( LocalHasUsuarioId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getLocalId()==castOther.getLocalId())
 && (this.getUsuarioId()==castOther.getUsuarioId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getLocalId();
         result = 37 * result + this.getUsuarioId();
         return result;
   }   


}


