package model;
// Generated Oct 25, 2017 6:15:37 PM by Hibernate Tools 4.3.1



/**
 * LocalHasUsuario generated by hbm2java
 */
public class LocalHasUsuario  implements java.io.Serializable {


     private LocalHasUsuarioId id;
     private Local local;
     private Usuario usuario;

    public LocalHasUsuario() {
    }

    public LocalHasUsuario(LocalHasUsuarioId id, Local local, Usuario usuario) {
       this.id = id;
       this.local = local;
       this.usuario = usuario;
    }
   
    public LocalHasUsuarioId getId() {
        return this.id;
    }
    
    public void setId(LocalHasUsuarioId id) {
        this.id = id;
    }
    public Local getLocal() {
        return this.local;
    }
    
    public void setLocal(Local local) {
        this.local = local;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


