package model;
// Generated Sep 21, 2017 5:31:36 AM by Hibernate Tools 4.3.1



/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private Integer id;
     private Perfil perfil;
     private String nombre;
     private String outcome;
     private char estado;

    public Modulo() {
    }

    public Modulo(Perfil perfil, String nombre, String outcome, char estado) {
       this.perfil = perfil;
       this.nombre = nombre;
       this.outcome = outcome;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOutcome() {
        return this.outcome;
    }
    
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


