package model;
// Generated Nov 13, 2017 12:33:12 PM by Hibernate Tools 4.3.1



/**
 * OrdenCompraHasPresentacionInsumoId generated by hbm2java
 */
public class OrdenCompraHasPresentacionInsumoId  implements java.io.Serializable {


     private int id;
     private int ordenCompraId;
     private int presentacionInsumoId;

    public OrdenCompraHasPresentacionInsumoId() {
    }

    public OrdenCompraHasPresentacionInsumoId(int id, int ordenCompraId, int presentacionInsumoId) {
       this.id = id;
       this.ordenCompraId = ordenCompraId;
       this.presentacionInsumoId = presentacionInsumoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getOrdenCompraId() {
        return this.ordenCompraId;
    }
    
    public void setOrdenCompraId(int ordenCompraId) {
        this.ordenCompraId = ordenCompraId;
    }
    public int getPresentacionInsumoId() {
        return this.presentacionInsumoId;
    }
    
    public void setPresentacionInsumoId(int presentacionInsumoId) {
        this.presentacionInsumoId = presentacionInsumoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdenCompraHasPresentacionInsumoId) ) return false;
		 OrdenCompraHasPresentacionInsumoId castOther = ( OrdenCompraHasPresentacionInsumoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getOrdenCompraId()==castOther.getOrdenCompraId())
 && (this.getPresentacionInsumoId()==castOther.getPresentacionInsumoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getOrdenCompraId();
         result = 37 * result + this.getPresentacionInsumoId();
         return result;
   }   


}


