package model;
// Generated Nov 13, 2017 12:33:12 PM by Hibernate Tools 4.3.1



/**
 * PerfilHasSubmenu generated by hbm2java
 */
public class PerfilHasSubmenu  implements java.io.Serializable {


     private PerfilHasSubmenuId id;
     private Perfil perfil;
     private Submenu submenu;

    public PerfilHasSubmenu() {
    }

    public PerfilHasSubmenu(PerfilHasSubmenuId id, Perfil perfil, Submenu submenu) {
       this.id = id;
       this.perfil = perfil;
       this.submenu = submenu;
    }
   
    public PerfilHasSubmenuId getId() {
        return this.id;
    }
    
    public void setId(PerfilHasSubmenuId id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Submenu getSubmenu() {
        return this.submenu;
    }
    
    public void setSubmenu(Submenu submenu) {
        this.submenu = submenu;
    }




}


