package model;
// Generated Oct 3, 2017 1:01:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private char estado;
     private Set perfilHasSubmenus = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(String nombre, char estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Perfil(String nombre, char estado, Set perfilHasSubmenus, Set usuarios) {
       this.nombre = nombre;
       this.estado = estado;
       this.perfilHasSubmenus = perfilHasSubmenus;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getPerfilHasSubmenus() {
        return this.perfilHasSubmenus;
    }
    
    public void setPerfilHasSubmenus(Set perfilHasSubmenus) {
        this.perfilHasSubmenus = perfilHasSubmenus;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


