package model;
// Generated Sep 21, 2017 5:31:36 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private char estado;
     private Set usuarios = new HashSet(0);
     private Set modulos = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(String nombre, char estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public Perfil(String nombre, char estado, Set usuarios, Set modulos) {
       this.nombre = nombre;
       this.estado = estado;
       this.usuarios = usuarios;
       this.modulos = modulos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }




}


