package model;
// Generated Sep 21, 2017 5:31:36 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer personaId;
     private String nombre;
     private String apellidop;
     private String apellidom;
     private String sexo;
     private String fechaNacimiento;
     private Set usuarios = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String nombre, String apellidop, String apellidom, String sexo, String fechaNacimiento) {
        this.nombre = nombre;
        this.apellidop = apellidop;
        this.apellidom = apellidom;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Persona(String nombre, String apellidop, String apellidom, String sexo, String fechaNacimiento, Set usuarios) {
       this.nombre = nombre;
       this.apellidop = apellidop;
       this.apellidom = apellidom;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.usuarios = usuarios;
    }
   
    public Integer getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(Integer personaId) {
        this.personaId = personaId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidop() {
        return this.apellidop;
    }
    
    public void setApellidop(String apellidop) {
        this.apellidop = apellidop;
    }
    public String getApellidom() {
        return this.apellidom;
    }
    
    public void setApellidom(String apellidom) {
        this.apellidom = apellidom;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


