package model;
// Generated Nov 13, 2017 12:33:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String nombreContacto;
     private String telefono;
     private String email;
     private char estado;
     private Set ordenCompras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, String nombreContacto, String telefono, String email, char estado) {
        this.nombre = nombre;
        this.nombreContacto = nombreContacto;
        this.telefono = telefono;
        this.email = email;
        this.estado = estado;
    }
    public Proveedor(String nombre, String nombreContacto, String telefono, String email, char estado, Set ordenCompras) {
       this.nombre = nombre;
       this.nombreContacto = nombreContacto;
       this.telefono = telefono;
       this.email = email;
       this.estado = estado;
       this.ordenCompras = ordenCompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getOrdenCompras() {
        return this.ordenCompras;
    }
    
    public void setOrdenCompras(Set ordenCompras) {
        this.ordenCompras = ordenCompras;
    }




}


