package model;
// Generated Oct 31, 2017 7:02:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Requerimiento generated by hbm2java
 */
public class Requerimiento  implements java.io.Serializable {


     private Integer id;
     private EstadoRequerimiento estadoRequerimiento;
     private Proveedor proveedor;
     private double montoTotal;
     private String observacion;
     private Date fechaRecepcion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set requerimientoHasPresentacionInsumos = new HashSet(0);

    public Requerimiento() {
    }

	
    public Requerimiento(EstadoRequerimiento estadoRequerimiento, Proveedor proveedor, double montoTotal) {
        this.estadoRequerimiento = estadoRequerimiento;
        this.proveedor = proveedor;
        this.montoTotal = montoTotal;
    }
    public Requerimiento(EstadoRequerimiento estadoRequerimiento, Proveedor proveedor, double montoTotal, String observacion, Date fechaRecepcion, Date fechaCreacion, Date fechaModificacion, Set requerimientoHasPresentacionInsumos) {
       this.estadoRequerimiento = estadoRequerimiento;
       this.proveedor = proveedor;
       this.montoTotal = montoTotal;
       this.observacion = observacion;
       this.fechaRecepcion = fechaRecepcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.requerimientoHasPresentacionInsumos = requerimientoHasPresentacionInsumos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EstadoRequerimiento getEstadoRequerimiento() {
        return this.estadoRequerimiento;
    }
    
    public void setEstadoRequerimiento(EstadoRequerimiento estadoRequerimiento) {
        this.estadoRequerimiento = estadoRequerimiento;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(double montoTotal) {
        this.montoTotal = montoTotal;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getRequerimientoHasPresentacionInsumos() {
        return this.requerimientoHasPresentacionInsumos;
    }
    
    public void setRequerimientoHasPresentacionInsumos(Set requerimientoHasPresentacionInsumos) {
        this.requerimientoHasPresentacionInsumos = requerimientoHasPresentacionInsumos;
    }




}


