package model;
// Generated Oct 31, 2017 7:02:24 PM by Hibernate Tools 4.3.1



/**
 * RequerimientoHasPresentacionInsumoId generated by hbm2java
 */
public class RequerimientoHasPresentacionInsumoId  implements java.io.Serializable {


     private int id;
     private int requerimientoId;
     private int presentacionInsumoId;

    public RequerimientoHasPresentacionInsumoId() {
    }

    public RequerimientoHasPresentacionInsumoId(int id, int requerimientoId, int presentacionInsumoId) {
       this.id = id;
       this.requerimientoId = requerimientoId;
       this.presentacionInsumoId = presentacionInsumoId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getRequerimientoId() {
        return this.requerimientoId;
    }
    
    public void setRequerimientoId(int requerimientoId) {
        this.requerimientoId = requerimientoId;
    }
    public int getPresentacionInsumoId() {
        return this.presentacionInsumoId;
    }
    
    public void setPresentacionInsumoId(int presentacionInsumoId) {
        this.presentacionInsumoId = presentacionInsumoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RequerimientoHasPresentacionInsumoId) ) return false;
		 RequerimientoHasPresentacionInsumoId castOther = ( RequerimientoHasPresentacionInsumoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getRequerimientoId()==castOther.getRequerimientoId())
 && (this.getPresentacionInsumoId()==castOther.getPresentacionInsumoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getRequerimientoId();
         result = 37 * result + this.getPresentacionInsumoId();
         return result;
   }   


}


