package model;
// Generated Oct 3, 2017 1:01:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String simbolo;
     private Set insumos = new HashSet(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(String nombre, String simbolo) {
        this.nombre = nombre;
        this.simbolo = simbolo;
    }
    public UnidadMedida(String nombre, String simbolo, Set insumos) {
       this.nombre = nombre;
       this.simbolo = simbolo;
       this.insumos = insumos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSimbolo() {
        return this.simbolo;
    }
    
    public void setSimbolo(String simbolo) {
        this.simbolo = simbolo;
    }
    public Set getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set insumos) {
        this.insumos = insumos;
    }




}


