package model;
// Generated Nov 7, 2017 10:59:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private Perfil perfil;
     private Persona persona;
     private String username;
     private String password;
     private String email;
     private char estado;
     private Set localHasUsuarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Persona persona, String username, String password, String email, char estado) {
        this.persona = persona;
        this.username = username;
        this.password = password;
        this.email = email;
        this.estado = estado;
    }
    public Usuario(Perfil perfil, Persona persona, String username, String password, String email, char estado, Set localHasUsuarios) {
       this.perfil = perfil;
       this.persona = persona;
       this.username = username;
       this.password = password;
       this.email = email;
       this.estado = estado;
       this.localHasUsuarios = localHasUsuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getLocalHasUsuarios() {
        return this.localHasUsuarios;
    }
    
    public void setLocalHasUsuarios(Set localHasUsuarios) {
        this.localHasUsuarios = localHasUsuarios;
    }




}


